### ISSUE TITLE
More JSON support

### ISSUE THREAD

**Issue by pdufour** [ericmann/dynamic-cdn#12]
So almost all the urls in WP-API v2 responses are getting rewritten except the json property values. Like so:

```
{
"content": "<img src='/foo.jpg' />",
"file": "/featured.jpg"
}
```

The `foo.jpg` get's replaced, but the `featured.jpg` does not since the regex requires a leading `=`. https://github.com/ericmann/dynamic-cdn/blob/master/includes/functions/core.php#L254.

There's a couple different ways to solve this so wanted to see what you thought.

**Option 1**
- Remove leading `=` in regex. So it will just require that the value be in quotes for it to be rewritten. I've seen similar regexes in a couple other libraries https://github.com/crowdfavorite-mirrors/wp-w3-total-cache/blob/53d0704bb0d8997b6ff692820cf935e7aae285da/lib/W3/Plugin/Cdn.php#L1009

**Option 2**
- Change the `=` to `[=:]` so it will match the featured.jpg.

I'd recommend Option 1 for the simplicity but there may be cases I am not thinking of. LMK what you think. I can put up a PR. Thanks.

**Comment by ericmann** [comment]
I think option 1 is better, particularly since it's consistent with what other libraries are doing.
